---
controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle"]
      max_vel_x: 0.26
      min_vel_x: -0.26
      max_vel_theta: 1.82
      min_vel_theta: -1.82

map_server:
  ros__parameters:
    yaml_filename: "/home/andrew-crispin/maps/my_map.yaml"  # Updated path

global_costmap:
  ros__parameters:
    global_costmap:
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        map_topic: map
      inflation_layer:
        inflation_radius: 0.55

local_costmap:
  ros__parameters:
    local_costmap:
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: true
          clearing: true

collision_monitor:
  ros__parameters:
    polygons: ["front"]
    front:
      type: "polygon"
      points: [0.3, 0.15, 0.3, -0.15, 0.0, -0.15, 0.0, 0.15]
      action_type: "slowdown"
      slowdown_percent: 0.3
    observation_sources: ["laser"]
    laser:
      type: "scan"
      topic: "/scan"
      min_height: 0.0
      max_height: 1.0

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]

behavior_server:
  ros__parameters:
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
